variable "namespace" {}
variable "kong_superuser_secret_name" {}
variable "kong_database_secret_name" {}
variable "kong_license_secret_name" {}
variable "kong_image" {}
variable "kong_database_host" {}
variable "kong_database_port" {}
variable "kong_database_user" {}
variable "kong_database_name" {}
